title: "keer4n.blog" 
name: "Kiran's blog"
author: Kiran Gurung 
twitter_username: keer4n 
description: Document my learning notes.
profile_url: "http://github.com/keer4n"
theme: jekyll-theme-primer

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
