title: Blog 
name: "Kiran's blog"
author: Kiran Gurung 
twitter_username: keer4n 
baseurl: "/"
description: Document my learning notes.
profile_url: "http://keer4n.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
